{
 "title": "Test",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Portfolio",
    "query": "SELECT DISTINCT portfolio_name FROM portfolios"
   },
   {
    "name": "pair",
    "query": "SELECT DISTINCT\n  concat(\n    '(',\n      char(39), symbol, char(39),\n      ',',\n      char(39), timeframe, char(39),\n    ')'\n  ) AS pair\nFROM ohlcv_data\n"
   },
   {
    "name": "indicators",
    "query": "avg(close) OVER (ORDER BY time ROWS BETWEEN 9 PRECEDING AND CURRENT ROW) AS sma_10,\navg(close) OVER (ORDER BY time ROWS BETWEEN 49 PRECEDING AND CURRENT ROW) AS sma_50"
   }
  ]
 },
 "panels": [
  {
   "title": "OHLCV – ${pair})",
   "type": "candlestick",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "repeat": "pair",
   "targets": [
    {
     "rawSql": "SELECT\r\n  symbol,\r\n  timeframe,\r\n  time,\r\n  open,\r\n  high,\r\n  low,\r\n  close,\r\n  volume,\r\n  ${indicators:raw}\r\nFROM ohlcv_data FINAL\r\nWHERE\r\n  tuple(symbol, timeframe) IN (${pair:raw})\r\nORDER BY symbol, timeframe, time\r\n"
    },
    {
     "rawSql": "SELECT\r\n  executed_at    AS time,\r\n  average_price  AS price,\r\n  order_side     AS side\r\nFROM orders o\r\nJOIN portfolios p ON o.portfolio_id = p.portfolio_id\r\nWHERE\r\n  p.portfolio_name = '${Portfolio}'\r\n  AND order_category = 'spot'\r\n  AND order_side = 'sell'\r\n  AND order_status = 'executed'\r\nORDER BY time\r\n"
    },
    {
     "rawSql": "SELECT\r\n  executed_at    AS time,\r\n  average_price  AS price,\r\n  order_side     AS side\r\nFROM orders o\r\nJOIN portfolios p ON o.portfolio_id = p.portfolio_id\r\nWHERE\r\n  p.portfolio_name = '${Portfolio}'\r\n  AND order_category = 'spot'\r\n  AND order_side = 'buy'\r\n  AND order_status = 'executed'\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "Asset Weight in Portfolio",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  arrayJoin(mapKeys(managed_assets)) AS asset,\r\n  toFloat64(managed_assets[asset]) * toFloat64(current_prices[asset]) AS value\r\nFROM portfolios\r\nWHERE portfolio_name = '${Portfolio}'"
    }
   ]
  },
  {
   "title": "Unrealized PnL",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  portfolio_name,\r\n  current_value - initial_balance AS unrealized_pnl\r\nFROM (\r\n  SELECT\r\n    portfolio_id,\r\n    any(portfolio_name) AS portfolio_name,\r\n    sum(toFloat64(managed_assets[asset]) * toFloat64(current_prices[asset])) AS current_value,\r\n    any(initial_balance) AS initial_balance\r\n  FROM portfolios\r\n  ARRAY JOIN mapKeys(managed_assets) AS asset\r\n  GROUP BY portfolio_id\r\n)"
    }
   ]
  },
  {
   "title": "Executed Orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time,\r\n  sum(executed_orders) OVER (ORDER BY time) AS cumulative_executed_orders\r\nFROM (\r\n  SELECT\r\n    toStartOfMinute(executed_at) AS time,\r\n    count() AS executed_orders\r\n  FROM orders\r\n  WHERE order_status = 'executed' AND created_at <= executed_at\r\n  GROUP BY time\r\n  ORDER BY time\r\n)\r\n"
    }
   ]
  }
 ]
}